// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package maskit

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransport creates a new instance of MockTransport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransport(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransport {
	mock := &MockTransport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransport is an autogenerated mock type for the Transport type
type MockTransport struct {
	mock.Mock
}

type MockTransport_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransport) EXPECT() *MockTransport_Expecter {
	return &MockTransport_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockTransport
func (_mock *MockTransport) Send(s string, maskingRequest MaskingRequest) (MaskingResponse, error) {
	ret := _mock.Called(s, maskingRequest)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 MaskingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, MaskingRequest) (MaskingResponse, error)); ok {
		return returnFunc(s, maskingRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(string, MaskingRequest) MaskingResponse); ok {
		r0 = returnFunc(s, maskingRequest)
	} else {
		r0 = ret.Get(0).(MaskingResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(string, MaskingRequest) error); ok {
		r1 = returnFunc(s, maskingRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransport_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockTransport_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - s string
//   - maskingRequest MaskingRequest
func (_e *MockTransport_Expecter) Send(s interface{}, maskingRequest interface{}) *MockTransport_Send_Call {
	return &MockTransport_Send_Call{Call: _e.mock.On("Send", s, maskingRequest)}
}

func (_c *MockTransport_Send_Call) Run(run func(s string, maskingRequest MaskingRequest)) *MockTransport_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MaskingRequest
		if args[1] != nil {
			arg1 = args[1].(MaskingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransport_Send_Call) Return(maskingResponse MaskingResponse, err error) *MockTransport_Send_Call {
	_c.Call.Return(maskingResponse, err)
	return _c
}

func (_c *MockTransport_Send_Call) RunAndReturn(run func(s string, maskingRequest MaskingRequest) (MaskingResponse, error)) *MockTransport_Send_Call {
	_c.Call.Return(run)
	return _c
}
