// Code generated by mockery v2.53.6. DO NOT EDIT.

package maskit

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockTransport is an autogenerated mock type for the Transport type
type MockTransport struct {
	mock.Mock
}

type MockTransport_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransport) EXPECT() *MockTransport_Expecter {
	return &MockTransport_Expecter{mock: &_m.Mock}
}

// DownloadImage provides a mock function with given fields: ctx, url
func (_m *MockTransport) DownloadImage(ctx context.Context, url string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for DownloadImage")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransport_DownloadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadImage'
type MockTransport_DownloadImage_Call struct {
	*mock.Call
}

// DownloadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockTransport_Expecter) DownloadImage(ctx interface{}, url interface{}) *MockTransport_DownloadImage_Call {
	return &MockTransport_DownloadImage_Call{Call: _e.mock.On("DownloadImage", ctx, url)}
}

func (_c *MockTransport_DownloadImage_Call) Run(run func(ctx context.Context, url string)) *MockTransport_DownloadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransport_DownloadImage_Call) Return(_a0 io.ReadCloser, _a1 error) *MockTransport_DownloadImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransport_DownloadImage_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockTransport_DownloadImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobStatus provides a mock function with given fields: ctx, url
func (_m *MockTransport) GetJobStatus(ctx context.Context, url string) (ImageStatusResponse, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStatus")
	}

	var r0 ImageStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (ImageStatusResponse, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) ImageStatusResponse); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(ImageStatusResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransport_GetJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobStatus'
type MockTransport_GetJobStatus_Call struct {
	*mock.Call
}

// GetJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockTransport_Expecter) GetJobStatus(ctx interface{}, url interface{}) *MockTransport_GetJobStatus_Call {
	return &MockTransport_GetJobStatus_Call{Call: _e.mock.On("GetJobStatus", ctx, url)}
}

func (_c *MockTransport_GetJobStatus_Call) Run(run func(ctx context.Context, url string)) *MockTransport_GetJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransport_GetJobStatus_Call) Return(_a0 ImageStatusResponse, _a1 error) *MockTransport_GetJobStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransport_GetJobStatus_Call) RunAndReturn(run func(context.Context, string) (ImageStatusResponse, error)) *MockTransport_GetJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, url, payload
func (_m *MockTransport) Send(ctx context.Context, url string, payload MaskingRequest) (MaskingResponse, error) {
	ret := _m.Called(ctx, url, payload)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 MaskingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, MaskingRequest) (MaskingResponse, error)); ok {
		return rf(ctx, url, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, MaskingRequest) MaskingResponse); ok {
		r0 = rf(ctx, url, payload)
	} else {
		r0 = ret.Get(0).(MaskingResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, MaskingRequest) error); ok {
		r1 = rf(ctx, url, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransport_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockTransport_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - payload MaskingRequest
func (_e *MockTransport_Expecter) Send(ctx interface{}, url interface{}, payload interface{}) *MockTransport_Send_Call {
	return &MockTransport_Send_Call{Call: _e.mock.On("Send", ctx, url, payload)}
}

func (_c *MockTransport_Send_Call) Run(run func(ctx context.Context, url string, payload MaskingRequest)) *MockTransport_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(MaskingRequest))
	})
	return _c
}

func (_c *MockTransport_Send_Call) Return(_a0 MaskingResponse, _a1 error) *MockTransport_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransport_Send_Call) RunAndReturn(run func(context.Context, string, MaskingRequest) (MaskingResponse, error)) *MockTransport_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransport creates a new instance of MockTransport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransport(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransport {
	mock := &MockTransport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
